apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: my-ns
spec: {}
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: printenv
  name: printenv
  namespace: my-ns
spec:
  containers:
  - image: ubuntu
    name: printenv
    command: ["printenv"]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
